<?php
/*
Plugin Name: Apicoder Doctor list
Plugin URI: https://apicoder.ru/doctorlist
Description: профессиональный плагин для WordPress, который позволяет создавать и управлять каталогом врачей. Плагин предоставляет удобную систему для отображения информации о врачах с возможностью фильтрации по городам и специализациям.
Version: 0.0.1
Author: Konstantin Milyushenko
Author URI: https://apicoder.ru
Text Domain: adl
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if (! defined('WPINC')) {
    die;
} // end if

// Let's Initialize Everything
if (file_exists(plugin_dir_path(__FILE__) . 'core-init.php')) {
    require_once(plugin_dir_path(__FILE__) . 'core-init.php');
}
